import { type NextRequest, NextResponse } from "next/server";
import type { User } from "@/lib/api/users";

const USERS: User[] = [
  {
    id: "u-001",
    name: "Andi Pratama",
    email: "andi.pratama@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-01-01",
  },
  {
    id: "u-002",
    name: "Siti Rahayu",
    email: "siti.rahayu@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-01-05",
  },
  {
    id: "u-003",
    name: "Budi Santoso",
    email: "budi.santoso@example.com",
    role: "Viewer",
    status: "Pending",
    joinedAt: "2025-01-10",
  },
  {
    id: "u-004",
    name: "Dewi Kusuma",
    email: "dewi.kusuma@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-01-15",
  },
  {
    id: "u-005",
    name: "Raka Wijaya",
    email: "raka.wijaya@example.com",
    role: "Viewer",
    status: "Ditangguhkan",
    joinedAt: "2025-01-20",
  },
  {
    id: "u-006",
    name: "Lina Maharani",
    email: "lina.maharani@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-02-01",
  },
  {
    id: "u-007",
    name: "Hendra Gunawan",
    email: "hendra.gunawan@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-02-05",
  },
  {
    id: "u-008",
    name: "Nurul Hidayah",
    email: "nurul.hidayah@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-02-10",
  },
  {
    id: "u-009",
    name: "Fajar Setiawan",
    email: "fajar.setiawan@example.com",
    role: "Viewer",
    status: "Pending",
    joinedAt: "2025-02-15",
  },
  {
    id: "u-010",
    name: "Ayu Wulandari",
    email: "ayu.wulandari@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-02-20",
  },
  {
    id: "u-011",
    name: "Rio Fernanda",
    email: "rio.fernanda@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-03-01",
  },
  {
    id: "u-012",
    name: "Maya Sari",
    email: "maya.sari@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-03-05",
  },
  {
    id: "u-013",
    name: "Dian Permata",
    email: "dian.permata@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-03-10",
  },
  {
    id: "u-014",
    name: "Agus Salim",
    email: "agus.salim@example.com",
    role: "Editor",
    status: "Ditangguhkan",
    joinedAt: "2025-03-15",
  },
  {
    id: "u-015",
    name: "Ratna Dewi",
    email: "ratna.dewi@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-03-20",
  },
  {
    id: "u-016",
    name: "Wahyu Hidayat",
    email: "wahyu.hidayat@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-04-01",
  },
  {
    id: "u-017",
    name: "Fitriani Amalia",
    email: "fitriani.amalia@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-04-05",
  },
  {
    id: "u-018",
    name: "Bagas Pramono",
    email: "bagas.pramono@example.com",
    role: "Viewer",
    status: "Pending",
    joinedAt: "2025-04-10",
  },
  {
    id: "u-019",
    name: "Indah Lestari",
    email: "indah.lestari@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-04-15",
  },
  {
    id: "u-020",
    name: "Rizky Ardiansyah",
    email: "rizky.ardiansyah@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-04-20",
  },
  {
    id: "u-021",
    name: "Yuni Kartika",
    email: "yuni.kartika@example.com",
    role: "Admin",
    status: "Ditangguhkan",
    joinedAt: "2025-04-25",
  },
  {
    id: "u-022",
    name: "Dimas Prasetyo",
    email: "dimas.prasetyo@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-05-01",
  },
  {
    id: "u-023",
    name: "Nadia Oktavia",
    email: "nadia.oktavia@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-05-05",
  },
  {
    id: "u-024",
    name: "Arif Rahman",
    email: "arif.rahman@example.com",
    role: "Editor",
    status: "Pending",
    joinedAt: "2025-05-10",
  },
  {
    id: "u-025",
    name: "Sisca Amelinda",
    email: "sisca.amelinda@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-05-15",
  },
  {
    id: "u-026",
    name: "Teguh Santoso",
    email: "teguh.santoso@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-05-20",
  },
  {
    id: "u-027",
    name: "Putri Anggraini",
    email: "putri.anggraini@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-05-25",
  },
  {
    id: "u-028",
    name: "Fauzan Aditya",
    email: "fauzan.aditya@example.com",
    role: "Viewer",
    status: "Ditangguhkan",
    joinedAt: "2025-06-01",
  },
  {
    id: "u-029",
    name: "Anggi Puspita",
    email: "anggi.puspita@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-06-05",
  },
  {
    id: "u-030",
    name: "Ridwan Fauzi",
    email: "ridwan.fauzi@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-06-10",
  },
  {
    id: "u-031",
    name: "Cantika Sari",
    email: "cantika.sari@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-06-15",
  },
  {
    id: "u-032",
    name: "Erlangga Putra",
    email: "erlangga.putra@example.com",
    role: "Admin",
    status: "Pending",
    joinedAt: "2025-06-20",
  },
  {
    id: "u-033",
    name: "Mirna Sulistyo",
    email: "mirna.sulistyo@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-06-25",
  },
  {
    id: "u-034",
    name: "Galih Permana",
    email: "galih.permana@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-07-01",
  },
  {
    id: "u-035",
    name: "Tiara Nasution",
    email: "tiara.nasution@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-07-05",
  },
  {
    id: "u-036",
    name: "Kevin Alfarizi",
    email: "kevin.alfarizi@example.com",
    role: "Viewer",
    status: "Ditangguhkan",
    joinedAt: "2025-07-10",
  },
  {
    id: "u-037",
    name: "Dita Maharani",
    email: "dita.maharani@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-07-15",
  },
  {
    id: "u-038",
    name: "Gilang Ramadhan",
    email: "gilang.ramadhan@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-07-20",
  },
  {
    id: "u-039",
    name: "Alya Nurzahwa",
    email: "alya.nurzahwa@example.com",
    role: "Viewer",
    status: "Pending",
    joinedAt: "2025-07-25",
  },
  {
    id: "u-040",
    name: "Hafiz Iskandar",
    email: "hafiz.iskandar@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-08-01",
  },
  {
    id: "u-041",
    name: "Vina Sabrina",
    email: "vina.sabrina@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-08-05",
  },
  {
    id: "u-042",
    name: "Adnan Khairul",
    email: "adnan.khairul@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-08-10",
  },
  {
    id: "u-043",
    name: "Citra Dewanti",
    email: "citra.dewanti@example.com",
    role: "Editor",
    status: "Ditangguhkan",
    joinedAt: "2025-08-15",
  },
  {
    id: "u-044",
    name: "Farhan Maulana",
    email: "farhan.maulana@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-08-20",
  },
  {
    id: "u-045",
    name: "Zara Aisyah",
    email: "zara.aisyah@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-08-25",
  },
  {
    id: "u-046",
    name: "Irwan Syahputra",
    email: "irwan.syahputra@example.com",
    role: "Editor",
    status: "Aktif",
    joinedAt: "2025-09-01",
  },
  {
    id: "u-047",
    name: "Mega Pratiwi",
    email: "mega.pratiwi@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-09-05",
  },
  {
    id: "u-048",
    name: "Satria Nugraha",
    email: "satria.nugraha@example.com",
    role: "Editor",
    status: "Pending",
    joinedAt: "2025-09-10",
  },
  {
    id: "u-049",
    name: "Renata Kusuma",
    email: "renata.kusuma@example.com",
    role: "Viewer",
    status: "Aktif",
    joinedAt: "2025-09-15",
  },
  {
    id: "u-050",
    name: "Yoga Adhitya",
    email: "yoga.adhitya@example.com",
    role: "Admin",
    status: "Aktif",
    joinedAt: "2025-09-20",
  },
];

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const page = Number.parseInt(searchParams.get("page") ?? "1", 10);
  const limit = Number.parseInt(searchParams.get("limit") ?? "10", 10);
  const search = (searchParams.get("search") ?? "").toLowerCase();
  const status = searchParams.get("status") ?? "";

  let filtered = USERS;

  if (search) {
    filtered = filtered.filter(
      (u) => u.name.toLowerCase().includes(search) || u.email.toLowerCase().includes(search)
    );
  }

  if (status) {
    filtered = filtered.filter((u) => u.status === status);
  }

  const total = filtered.length;
  const start = (page - 1) * limit;
  const data = filtered.slice(start, start + limit);

  await new Promise((r) => setTimeout(r, 150));

  return NextResponse.json({
    data,
    meta: {
      page: {
        total,
        current: page,
        perPage: limit,
        totalPages: Math.max(1, Math.ceil(total / limit)),
      },
    },
  });
}
